### PR TITLE
Slider feels a lot snappier and natural

### PR DESCRIPTION
**Pull request by vjoao**
I've added 
- dynamic transition times based on swipe ending velocity
- easeOut animation curve for smoother transitions
- end-of-gesture transition, so the user is not surprised by the transition when still dragging

And refactored some stuff.

### CODE REVIEW

**Comment by TheOriginalJosh** [comment]
Awesome! For adding this. Makes sure to add yourself to the package.json contributors section. I'll pull this down here in a bit and test, but at first glance it looks like there shouldn't be a problem. What's your NPM user name? I will add you to the contributors there as well.

**Comment by TheOriginalJosh** [comment]
Oh what are your thoughts on making the animation curve an optional attribute for the end user? I had been toying with that the other day, but  animations like spring where causing.... fuglyness. So inwas thinking for the time being  asding an  enum with only ease in, out and linear? Then maybe later on write our own spring animation that could be an enum but is taken on on the end. Just some ideas.

**Comment by vjoao** [comment]
Optional curves sounds cool. Also, we should make the transition time optional when doing nextSlide() / previousSlide() so one can set the slide change velocity when doing it via buttons.

**Comment by vjoao** [comment]
I'm @vjoao on npm as well.

**Comment by TheOriginalJosh** [comment]
Good idea! I think there is a bug in there with the nextSlide and previousSlide functions that are messing up the positioning but haven't found yet. 

Oh one thing I want to start doing is when making a pr always create a new branch. Can you switch this to new branch, name isn't big deal matter. It will just help keep this morning organised since there are a couple people contributing. I need to buy together some. simple contribution guide lines.

Thanks again man, this looks great.

**Comment by vjoao** [comment]
Oh, sure... branches are important, sorry to forget about that. 
This plugin looks really promising with lots of use cases, thank you =)

**Comment by TheOriginalJosh** [comment]
No worries about the branch man, it's something I haven't been asking others to do but needed too. This is a bigger PR so a good place to start.

**Comment by vjoao** [comment]
I'll check the next/previous positioning bug

**Comment by vjoao** [comment]
I cant reproduce the positioning bug, but there is one on calling previousSlide when on first slide or nextSlide when on last one.

**Comment by vjoao** [comment]
Moving this to a new branch.

**Pull request closed without merging**
