### PR TITLE
disablepan done

### PR DESCRIPTION
**Pull request by Obsessive**

### CODE REVIEW

**Comment by Obsessive** [comment]
Does this plugin has a feature like if I call a function by passing a number then corresponding slide will be shown?

**Comment by Obsessive** [comment]
I have changed the code to solve issue#23

**Comment by TheOriginalJosh** [comment]
@Obsessive  Thanks man!

**Comment by Obsessive** [comment]
you can close issue #23 now

**Comment by Obsessive** [comment]
Does this plugin has a feature like if I call a function by passing a number then corresponding slide will be shown?

**Comment by TheOriginalJosh** [comment]
Not at this moment, but I'm working on it.

**Pull request merged**
