### PR TITLE
updated readme.md for nativescript v2.0.1

### PR DESCRIPTION
**Pull request by Obsessive**

### CODE REVIEW

**Comment by TheOriginalJosh** [comment]
Hey man thanks you for adding this. I'm a little confused though. Currently with NS 2.0.1 the panning I'd already updated, so I don't want us to be telling that they should change their node_modules around if the don't need to be.

I'm on my phone at the moment though, so it's kinda hard to read the Markdown.

**Comment by bradmartin** [comment]
Yea I have to agree, this isn't necessary with 2.0.1 as @TheOriginalJosh had a PR accepted by the NativeScript team and they refactored much of the gesture logic. That change is only pre 2.0.1 👍

**Comment by Obsessive** [comment]
Added disable pan feature. Can you check it once.

**Comment by TheOriginalJosh** [comment]
Hey @Obsessive hows it going? thanks for PR. Could you do me a favor, and re-submit this PR on a new branch. I'm trying to keep this a little more organized since there are multiple contributors and the branches will help. This disable panning sounds handy. Oh and please make sure to pull before merging to avoid any conflicts.

Cheers!

**Comment by Obsessive** [comment]
Ok

**Comment by TheOriginalJosh** [comment]
Thanks @obsessive

**Pull request closed without merging**
