### PR TITLE
Added the interval feature

### PR DESCRIPTION
**Pull request by Obsessive**
Now the slides will change on regular interval.

### CODE REVIEW

**Comment by Obsessive** [comment]
Hi, can you add that this plugin is also a carousel in the nativescript rocks plugin description because now it also has a feature of slideshow.

**Comment by TheOriginalJosh** [comment]
@Obsessive this looks great! I'll test it with it this evening, in the meantime feel free to add your self as a contributor to the package.json file. n
Thanks again!

**Comment by Obsessive** [comment]
Thanks man

**Comment by TheOriginalJosh** [comment]
@Obsessive What are you thoughts about renaming the plugin to just slides. I feel like it will continue expanding past the original use case, and rather do it now since as intro slides it's pretty stable.

**Comment by Obsessive** [comment]
When i started working on nativescript i needed a carousel view for the app just like bootstrap carousel which is available for websites then i found your plugin and used setinterval function to mimic it. So, I think nativescript-carousel would be a good name and nativescript-slides is also a good name because it is more than a image carousel. We can add any element into it like buttons, dropdowns, switches, segmentedbars, lists and so on.And finally it is your call. Thanks for asking my opinion man.

**Comment by TheOriginalJosh** [comment]
@Obsessive when you have a chance could you pull down the latest version, I've changed the project name and it's created a merge conflict. Sorry :(

**Comment by Obsessive** [comment]
Ok

**Comment by Obsessive** [comment]
Can you take a glance at the code to avoid any copy paste mistake i might have made.

**Comment by TheOriginalJosh** [comment]
It looks like in the merge reverted some fo the name changes.

**Comment by Obsessive** [comment]
Ok i will change them and send the new files.

**Comment by TheOriginalJosh** [comment]
@Obsessive  Thank you I appreciate it. :)

**Comment by TheOriginalJosh** [comment]
Github is still complaining about a merge conflict. If it's still I problem I'll take a look tonight.

**Comment by Obsessive** [comment]
can you post the link to view the conflicts

**Comment by TheOriginalJosh** [comment]
@Obsessive It looks like we are good now! I'm going to merge it and tonight I'll publish. Thanks again man!

**Comment by Obsessive** [comment]
Ok

**Pull request merged**
